### ISSUE TITLE
About header usage

### ISSUE THREAD

**Issue by yakuter** [netinternet/remoteaddr#2]
Headers are normally maps (key, value objects). So I think the Header field of Addr should be map instead of []string. However I don't know the exact usage of the package, I can be wrong about this request.

**Comment by osmanmakal** [comment]
Thank you for your contribution. #1

**Comment by yakuter** [comment]
@osmanmakal you closed the issue however this issue is different from my PR about tests :)

**Comment by osmanmakal** [comment]
I am sorry for the confusion

**Comment by osmanmakal** [comment]
> Headers are normally maps (key, value objects). So I think the Header field of Addr should be map instead of []string. However I don't know the exact usage of the package, I can be wrong about this request.

In http server applications written with Go, if a proxy is used, the user IP address tool cannot be obtained from the remote_addr header. Because it will be the proxy server IP address written here. Apart from the remote_addr header, which is used by default to reach the real IP address, many different header information can be checked. While the similar headers ones are kept in the software, the ones customized by the users are specified as headers in the module.

Reason for specifying it as a string; If there is more than one proxy server in the background, it will be a problem to reach the real IP address, so we need to find IP addresses by checking all listed IP addresses according to Forwarders list.
